name: flutter_notion_avatar
description: An flutter widget plugin notion-style avatars
version: 0.0.5
homepage: https://github.com/lowapple/flutter-notion-avatar

environment:
  sdk: ">=2.18.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.3.1

flutter:
  assets:
    - assets/
    # components
    - assets/avatar/components/accessories/
    - assets/avatar/components/beard/
    - assets/avatar/components/details/
    - assets/avatar/components/eyebrows/
    - assets/avatar/components/eyes/
    - assets/avatar/components/face/
    - assets/avatar/components/festival/christmas/
    - assets/avatar/components/festival/halloween/
    - assets/avatar/components/glasses/
    - assets/avatar/components/hair/
    - assets/avatar/components/mouth/
    - assets/avatar/components/nose/
    # preview
    - assets/avatar/preview/accessories/
    - assets/avatar/preview/beard/
    - assets/avatar/preview/details/
    - assets/avatar/preview/eyebrows/
    - assets/avatar/preview/eyes/
    - assets/avatar/preview/face/
    - assets/avatar/preview/festival/christmas/
    - assets/avatar/preview/festival/halloween/
    - assets/avatar/preview/glasses/
    - assets/avatar/preview/hair/
    - assets/avatar/preview/mouth/
    - assets/avatar/preview/nose/

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    output:
      package_parameter_enabled: true

topics:
  - avatar
  - notion
